org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# 环境属性
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.75

# 模组属性
mod_id=dmonsters
mod_name=Deadly Monsters: Modern
mod_license=MIT
mod_version=1.0-26.2
mod_group_id=com.dmonsters
