license="${mod_license}"
issueTrackerURL="https://github.com/HansOffice/deadly-monsters-modern/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/HansOffice/deadly-monsters-modern"
authors="bigbang87（原作者）, HansOffice（1.21.1 移植）"
description='''
Deadly Monsters 原版 Minecraft 1.12.2 模组的 NeoForge 1.21.1 移植版
保留原版注册标识、资源与玩法内容
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
